# Generated by Django 4.2.4 on 2023-10-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fichierIPFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=100)),
                ('datedajout', models.DateTimeField(auto_now_add=True)),
                ('nomFichier', models.CharField(max_length=100)),
                ('taillefichier', models.CharField(max_length=100)),
            ],
        ),
    ]
